language: ruby
before_install:
  - gem update --system
  - gem install bundler
gemfile:
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1
  - 2.7.2
script:
  - bundle exec rspec
